title: Jay From Future's Blog (but not about future or futures)
email: jay.from.future@gmail.com
description: >-
  Dark times lie ahead of us and there will be a time when we must choose between what is easy and what is right.
  (Albus Dumbledore, Harry Potter and the Goblet of Fire)
baseurl: ""
url: "https://jay-from-future.github.io/"
twitter_username:
github_username: jay-from-future

# Build settings
theme: jekyll-theme-midnight
plugins: []
show_excerpts: true